BaseUrl= "http://cronop.io/"
LanguageCode= "es-CO"
Title= "Colombia, mi tierra querida"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2018"
canonifyurls = true
theme="hugo-theme-air"

[params]
  description = "Lugares hermosos a donde quiera que vayas."
  cover = "images/user.jpg"
  author = "cronopio"
  authorlocation = "Colombia"
  authorwebsite = "http://cronop.io"
  bio= "Quiero compartir los lugares hermosos que he podido visitar de Colombia y del Mundo"
  logo = "images/user.png"
  googleAnalyticsUserID = "UA-45280129-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "cronopio"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
